package com.example.pokemon

import cats.effect.{Concurrent, Async}
import cats.syntax.all.*
import cats.effect.std.Console
import fs2.io.file.Files
import org.http4s.{HttpRoutes, DecodeFailure, Request}
import org.http4s.dsl.Http4sDsl

import org.http4s.server.staticcontent._
import org.http4s.StaticFile

import com.example.pokemon.routes.*
import com.example.pokemon.data.{UserLikeRequest, UserLoginRequest}

object PokemonRoutes {

  /*!
  * ====================================================================================================
  * ====================================================================================================
  * =====================================          FILES          ======================================
  * ====================================================================================================
  * ====================================================================================================
  */

  /**
    *  GET /
    *  @Response: index.html
    */
  def indexHTML[F[_] : Async: Files]: HttpRoutes[F] = {
    val dsl = new Http4sDsl[F]{}
    import dsl.*;

    HttpRoutes.of[F] {
      case req @ (GET -> Root) => {
        StaticFile.fromPath (
          fs2.io.file.Path ("resources/index.html"),
          Some (req)
        ).getOrElseF (NotFound ())
      }
    }
  }

  /**
    * Serve all other resource files
    */
  def homeResources[F[_] : Async: Files]: HttpRoutes[F] = {
    fileService[F](FileService.Config(
      systemPath = "resources/"
    ))
  }

  /**
  * JS generated by the frontend
    */
  def frontendResources[F[_] : Async: Files]: HttpRoutes[F] = {
    fileService[F](FileService.Config(
      systemPath = "frontend/target/scala-3.6.4/",
      pathPrefix = "/scripts"
    ))
  }

  /*!
  * ====================================================================================================
  * ====================================================================================================
  * ======================================          API          =======================================
  * ====================================================================================================
  * ====================================================================================================
  */

  /**
    * Pokemon information page :
    * - Get /api/pokemon-info/{name}    
    */
  def pokemonInformation[F[_] : Concurrent](M : PokemonInformation[F]): HttpRoutes[F] = {
    val dsl = new Http4sDsl[F]{}
    import dsl.*;
    HttpRoutes.of[F] {
      case GET -> Root / "api"/ "pokemon-info" / name => {        
        M.get(name)
          .flatMap {
            result => Ok (result)
          }.handleErrorWith {
            case PokemonInformationError(t) =>
              NotFound()
          }        
      }
    }
  }

  /**
    * List pokemon names starting with {name}
    * Get /api/pokemon-lists/{name}
    */
  def suggestPokemons[F[_]: Concurrent: Console](M: PokemonInformation[F]): HttpRoutes[F] = {
    val dsl = new Http4sDsl[F]{}
    import dsl.*;
    HttpRoutes.of[F] {
      case GET -> Root / "api"/ "pokemon-lists" / name => {
        M.suggest(name)
          .flatMap {
            result => Ok (result)
          }.handleErrorWith {
            case _ =>
              NotFound()
          }
      }
    }
  }

  /**
    * POST /api/login
    * @Request : {
    *    "login" : String
    *    "password" : String
    * }
    * @Response : {
    *    "id" : Int
    *    "name" : String
    *    "jwt" : String
    * }
    */
  def loginUser[F[_] : Concurrent](M : UserManager[F]): HttpRoutes[F] = {
    val dsl = new Http4sDsl[F]{}
    import dsl.*;
    HttpRoutes.of[F] {
      case req @ (POST -> Root / "api" / "login") => {
        (for {
          body <- req.as[UserLoginRequest] // Decode the json request
          resp <- M.login (body.login, body.password) // Send to the controller
          result <- Ok (resp) // Ok 
        } yield result).handleErrorWith {
          // JSON decoding error case
          case df: DecodeFailure =>
            BadRequest(s"Invalid JSON: ${df.getMessage}")

          // Login fail or else
          case _: UserError =>
            Forbidden("Log failed")

          // unexpected errors
          case e =>
            InternalServerError(s"Unexpected error: ${e}")
        }
      }
    }
  }

  /**
    * POST /api/like
    * @Request: {
    *    "userId" : Int
    *    "pokemonId" : Int
    *    "jwt" : String
    * }
    * @Response: Unit
    */
  def likePokemon[F[_] : Concurrent: Console](M : UserManager[F]): HttpRoutes[F] = {
    val dsl = new Http4sDsl[F]{}
    import dsl.*;
    HttpRoutes.of[F] {
      case req @ (POST -> Root / "api" / "like") => {
        (for {
          body <- req.as[UserLikeRequest]          
          _ <- M.like (body.userId, body.jwt, body.pokemonId)
          result <- Ok ()
        } yield result).handleErrorWith {
          // JSON decoding error case
          case df: DecodeFailure =>
            BadRequest(s"Invalid JSON: ${df.getMessage}")

          // Not connected
          case _: UserError =>
            Forbidden("Must be connected")

          // unexpected errors
          case e =>
            InternalServerError(s"Unexpected error: ${e}")           
        }
      }
    }
  }


}
